Repository mtripg6666tdr/Discord-SimpleMusicBot, pull requests merged in 2023-05, with the labels that each got.

#1548 Chore(dependabot.yml): ignore major updates of `prism-react-renderer`
  .github/dependabot.yml
Labels: chore

#1561 Chore(dependabot.yml): ignore major updates of https-proxy-agent on v1 and v3
  .github/dependabot.yml
Labels: chore

#1568 Fix: wrong logging tags
  src/Structure/GuildDataContainer.ts
  src/Structure/LogEmitter.ts
  src/Util/index.ts
  src/logger.ts
Labels: bug

#1569 Feat: expand spotify shorten links
  src/AudioSource/spotify.ts
  src/Structure/GuildDataContainer.ts
Labels: enhancement

#1570 Feat: support flac audio as custom stream
  src/Util/index.ts
Labels: enhancement

#1571 Feat: bot whitelist
  config.json.sample
  docs/docs/setup/installation/configuration.md
  src/Commands/import.ts
  src/Structure/GuildDataContainer.ts
  src/config/index.ts
  src/config/type.ts
Labels: enhancement

#1572 Feat: hide source urls in particular conditions
  src/AudioSource/audiosource.ts
  src/AudioSource/bestdori.ts
  src/AudioSource/custom.ts
  src/Commands/export.ts
  src/Commands/nowplaying.ts
  src/Commands/queue.ts
  src/Component/AudioResource.ts
  src/Component/PlayManager.ts
  src/Component/QueueManager.ts
  src/Structure/GuildDataContainer.ts
Labels: enhancement

#1576 Feat: search niconico video
  docs/docs/guide/commands/searchniconico.md
  locales/ja/commands.json
  src/Commands/searchniconico.ts
  src/Component/SearchPanel.ts
Labels: enhancement

#1577 Fix: no samplingrate passed to ffmpeg when loudnorm and volume transforming enabled
  src/Component/streams/ffmpeg.ts
Labels: bug

#1578 Fix: behavior of getting private file urls
  src/Component/PlayManager.ts
  src/Util/index.ts
Labels: bug

#1579 Feat: count voicemembers with excluding bots on voiceChannelLeave event
  src/events/voiceChannelLeave.ts
Labels: enhancement

#1581 Fix: handle promise rejection correctly
  src/Component/SearchPanel.ts
  src/Component/SourceCache.ts
  src/Component/backupper/replit.ts
Labels: bug

#1582 Chore: update tsconfig
  package-lock.json
  package.json
  src/Component/streams/normalizer.ts
  tsconfig.build.json
  tsconfig.json
Labels: chore

#1584 Change(i18n): sync translations from Crowdin
  locales/en-US/commands.json
Labels: language

#1588 Docs: add description of `PORT` in env
  docs/docs/setup/installation/configuration.md
Labels: documentation

#1586 Fix: messages when users doesn't meet required permissions
  package-lock.json
  package.json
  src/Commands/index.ts
  src/handlers/buttonInteraction.ts
  src/handlers/commandInteraction.ts
Labels: bug

#1589 Change(commands/searchnico): change slash command
  docs/docs/guide/commands/searchnico.md
  src/Commands/searchnico.ts
Labels: change

#1590 Change(i18n): sync translations from Crowdin
  docs/docs/guide/commands/searchnico.md
  locales/en-GB/commands.json
  locales/en-US/commands.json
  locales/fr-FR/commands.json
  locales/ja/commands.json
  locales/th-TH/commands.json
  locales/zh-TW/commands.json
Labels: language

#1599 Feat: bulk_delete is now available from slash commands!
  docs/docs/guide/commands/bulk_delete.md
  locales/ja/commands.json
  src/Commands/bulkdelete.ts
  src/Component/CommandManager.ts
Labels: enhancement

#1600 Chore(gitattributes): collapse versioned docs in diff
  .gitattributes
Labels: chore

#1601 Change(i18n): sync translations from Crowdin
  docs/docs/guide/commands/bulk_delete.md
  docs/docs/guide/commands/play_private.md
  locales/en-GB/commands.json
  locales/en-US/commands.json
  locales/fr-FR/commands.json
  locales/ja/commands.json
  locales/th-TH/commands.json
  locales/zh-TW/commands.json
  src/Commands/bulkdelete.ts
  util/generateCommandList.js
Labels: language

#1630 Docs: miscellaneous documentation
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .github/SUPPORT.md
  README.md
  docs/docs/setup/support.md
  docs/docs/setup/whatsnext.md
  docs/versioned_docs/version-v3.10/setup/whatsnext.md
  docs/versioned_docs/version-v3.11/setup/whatsnext.md
  docs/versioned_docs/version-v3.3/setup/whatsnext.md
  docs/versioned_docs/version-v3.4/setup/whatsnext.md
  docs/versioned_docs/version-v3.5/setup/whatsnext.md
  docs/versioned_docs/version-v3.6/setup/whatsnext.md
  docs/versioned_docs/version-v3.7/setup/whatsnext.md
  docs/versioned_docs/version-v3.8/setup/whatsnext.md
  docs/versioned_docs/version-v3.9/setup/whatsnext.md
  docs/versioned_docs/version-v4.0/setup/whatsnext.md
Labels: documentation

#1631 Feat: configurable help
  src/@types/node.d.ts
  src/Commands/help.ts
Labels: enhancement

#1632 Docs: fix typo
  docs/docs/setup/support.md
Labels: documentation

#1634 Fix: stops radio correctly
  locales/ja/commands.json
  src/Commands/radio.ts
Labels: bug

#1636 Feat: limit mem cache count
  src/Component/SourceCache.ts
Labels: enhancement

#1637 Docs: fix typo
  docs/docs/guide/feature/radio.md
  docs/docs/setup/support.md
Labels: documentation

#1638 Docs: generate command-list
  docs/docs/guide/commands/bgm.md
  docs/docs/guide/commands/bulk_delete.md
  docs/docs/guide/commands/cancel.md
  docs/docs/guide/commands/command.md
  docs/docs/guide/commands/disconnect.md
  docs/docs/guide/commands/effect.md
  docs/docs/guide/commands/end.md
  docs/docs/guide/commands/equalplayback.md
  docs/docs/guide/commands/export.md
  docs/docs/guide/commands/frame.md
  docs/docs/guide/commands/help.md
  docs/docs/guide/commands/import.md
  docs/docs/guide/commands/invoke.md
  docs/docs/guide/commands/join.md
  docs/docs/guide/commands/leaveclean.md
  docs/docs/guide/commands/log.md
  docs/docs/guide/commands/loop.md
  docs/docs/guide/commands/looponce.md
  docs/docs/guide/commands/loopqueue.md
  docs/docs/guide/commands/lyrics.md
  docs/docs/guide/commands/move.md
  docs/docs/guide/commands/movelastsongtofirst.md
  docs/docs/guide/commands/news.md
  docs/docs/guide/commands/nowplaying.md
  docs/docs/guide/commands/overview.md
  docs/docs/guide/commands/pause.md
  docs/docs/guide/commands/ping.md
  docs/docs/guide/commands/play.md
  docs/docs/guide/commands/play_private.md
  docs/docs/guide/commands/queue.md
  docs/docs/guide/commands/radio.md
  docs/docs/guide/commands/related.md
  docs/docs/guide/commands/remove.md
  docs/docs/guide/commands/removeall.md
  docs/docs/guide/commands/removedupes.md
  docs/docs/guide/commands/reset.md
  docs/docs/guide/commands/rewind.md
  docs/docs/guide/commands/search.md
  docs/docs/guide/commands/searchnico.md
  docs/docs/guide/commands/searchqueue.md
  docs/docs/guide/commands/searchsoundcloud.md
  docs/docs/guide/commands/seek.md
  docs/docs/guide/commands/shuffle.md
  docs/docs/guide/commands/skip.md
  docs/docs/guide/commands/thumbnail.md
  docs/docs/guide/commands/uptime.md
  docs/docs/guide/commands/volume.md
  docs/docs/setup/support.md
  docs/docusaurus.config.js
  docs/src/css/custom.css
  util/generateCommandList.js
Labels: documentation

#1640 Docs: move command link, discordportals link add
  .env.sample
  README.md
  locales/README.en-US.md
  locales/README.fr-FR.md
  locales/README.th-TH.md
  locales/README.zh-TW.md
Labels: documentation

#1645 Add(commands/help): search nico
  src/Commands/help.ts
Labels: enhancement

#1646 Fix: cannot read properties of null; reading 'acknowledged'
  src/Commands/index.ts
Labels: bug

#1647 Bump: package version to v4.1.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, bump

#1649 Fix: broken interaction collector
  src/Component/collectors/InteractionCollectorManager.ts
  src/handlers/buttonInteraction.ts
  src/handlers/selectMenuInteraction.ts
Labels: bug

#1650 Bump: package version to v4.1.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, bump

#1673 Docs: bgm has no longer been beta already
  docs/docs/setup/feature/3-bgm.md
  docs/versioned_docs/version-v4.0/setup/feature/bgm.md
  docs/versioned_docs/version-v4.1/setup/feature/3-bgm.md
Labels: documentation

#1705 Update: bump oceanic.js from 1.6.0 to 1.7.0
  package-lock.json
  package.json
  src/Commands/bulk_delete.ts
  src/Commands/import.ts
  src/Commands/index.ts
  src/Commands/play_private.ts
  src/Component/CommandManager.ts
  src/Component/QueueManager.ts
  src/Component/collectors/InteractionCollector.ts
  src/Component/collectors/InteractionCollectorManager.ts
  src/Component/collectors/Pagenation.ts
  src/Structure/GuildDataContainer.ts
  src/Util/discord.ts
  src/handlers/buttonInteraction.ts
Labels: dependencies, javascript

#1706 Chore(eslint): re-configure eslint
  .eslintrc.json
  package-lock.json
  package.json
  src/Commands/log.ts
  src/Commands/lyrics.ts
  src/Commands/news.ts
  src/Commands/ping.ts
  src/Component/BinaryManager.ts
  src/Component/PlayManager.ts
  src/Component/QueueManager.ts
  src/Component/SkipManager.ts
  src/Component/SourceCache.ts
  src/Component/backupper/mongodb.ts
  src/Structure/GuildDataContainer.ts
  src/Util/decorators.ts
Labels: chore
