Repository mtripg6666tdr/Discord-SimpleMusicBot, pull requests merged in 2023-10, with the labels that each got.

#2033 Fix: custom stream abort
  src/AudioSource/custom.ts
  src/Util/index.ts
Labels: bug

#2048 Fix: support direct audio urls with query strings
  src/AudioSource/custom.ts
  src/Util/index.ts
Labels: bug

#2050 Docs: fix typo and some improvements
  docs/docs/guide/feature/radio.md
  docs/docs/guide/tutorial.md
  docs/versioned_docs/version-v4.1/guide/feature/radio.md
  docs/versioned_docs/version-v4.1/guide/tutorial.md
  docs/versioned_docs/version-v4.1/setup/installation/configuration.md
Labels: documentation

#2051 Chore: check PR titles on ci
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-checker.yml
Labels: chore

#2052 Bump: package version to v4.1.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, bump

#1494 Improve: change workflows to Node.js v20
  .github/workflows/deploy-docs.yml
  .github/workflows/fix-lint-errors.yml
  .github/workflows/minor-release.yml
  .github/workflows/node-db-test.yml
  .github/workflows/patch-release.yml
  .github/workflows/release-notification.yml
  .github/workflows/test.yml
Labels: chore
