Repository mtripg6666tdr/Discord-SimpleMusicBot, pull requests merged in 2023-04, with the labels that each got.

#1323 Fix: get localized description correctly
  src/Commands/index.ts
Labels: bug

#1324 Change: update translations
  locales/en-US/commands.json
Labels: language

#1325 Bump: package version to v4.0.0-beta.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bump

#1326 Fix: localize button labels on control panel
  locales/ja/components.json
  src/Component/PlayManager.ts
  src/Component/SkipManager.ts
Labels: bug

#1327 Change: update translations
  locales/en-US/commands.json
  locales/en-US/components.json
  locales/fr-FR/components.json
Labels: language

#1328 Fix: missing translation
  src/Component/SkipManager.ts
Labels: bug

#1331 Chore: fix lint errors automatically
  .github/workflows/fix-lint-errors.yml
Labels: chore, target:v3

#1332 Chore: fix lint errors automatically
  .github/workflows/fix-lint-errors.yml
Labels: chore

#1330 Change: update translations
  .github/workflows/fix-lint-errors.yml
  docs/docs/guide/commands/skip.md
  locales/en-US/commands.json
  locales/en-US/components.json
  locales/fr-FR/commands.json
  locales/ja/commands.json
  src/i18n.ts
Labels: language

#1333 Fix: cost calculation
  src/Commands/log.ts
  src/Component/streams/index.ts
Labels: bug

#1329 Bump: package version to v4.0.0-beta.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bump

#1334 Fix: volume not working
  src/Component/AudioResource.ts
  src/Component/PlayManager.ts
Labels: bug

#1335 Fix: use dependent label in message commands
  locales/ja/commands.json
  src/Commands/index.ts
Labels: bug

#1336 Change: update translations
  locales/en-US/commands.json
  locales/en-US/default.json
  locales/fr-FR/commands.json
Labels: language

#1337 Bump: package version to v4.0.0-beta.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bump

#1338 Fix(compose): typo
  docker-compose.yml.sample
Labels: chore

#1339 Fix(compose): hostname of db
  docker-compose.yml.sample
Labels: bug

#1340 Fix: wrong playlist processing message
  src/Structure/GuildDataContainer.ts
Labels: bug

#1343 Chore(crowdin.yml): fix readme mapping
  crowdin.yml
Labels: chore

#1344 Change(commands/loopqueue): prefer `loopqueue` to `queueloop`
  docs/docs/guide/commands/loopqueue.md
  src/Commands/loopqueue.ts
Labels: change

#1345 Fix(commands/commands): remove duped command names
  src/Commands/commands.ts
Labels: bug

#1347 Change: update translations
  docs/docs/guide/commands/import.md
  docs/docs/guide/commands/search.md
  locales/en-US/commands.json
  locales/fr-FR/commands.json
  locales/ja/commands.json
  locales/th-TH/commands.json
  locales/zh-TW/commands.json
Labels: language

#1348 Docs: add i18n readme links
  README.md
Labels: documentation

#1352 Docs: update tutorial
  docs/docs/guide/tutorial.md
Labels: documentation

#1353 Update: deps
  package-lock.json
  package.json
Labels: dependencies, javascript

#1354 Feat: auto-resume on voice-channel join
  src/Component/PlayManager.ts
  src/events/voiceChannelJoin.ts
  src/events/voiceChannelLeave.ts
Labels: enhancement

#1355 Fix: fallbacking stream interruption
  src/AudioSource/youtube/strategies/play-dl.ts
Labels: bug

#1358 Change: update translations
  locales/en-US/commands.json
  locales/fr-FR/commands.json
  locales/fr-FR/default.json
  locales/ja/commands.json
  locales/ja/default.json
  locales/th-TH/commands.json
  locales/th-TH/default.json
  locales/zh-TW/commands.json
  locales/zh-TW/default.json
Labels: language

#1356 Feat: purge stale caches automatically
  src/Component/SourceCache.ts
  src/config/index.ts
  src/config/type.ts
  src/logger.ts
Labels: enhancement

#1359 Fix: rate-limitting bucket bug (workaround)
  locales/ja/commands.json
  src/Commands/reset.ts
  src/Commands/search.ts
  src/Component/PlayManager.ts
  src/Component/QueueManager.ts
  src/Structure/Command.ts
Labels: bug

#1360 Docs: add new configurations
  config.json.sample
  docs/docs/setup/installation/configuration.md
  src/config/index.ts
Labels: documentation

#1367 Docs: use consistent branch name in dependency badge
  README.md
Labels: documentation, target:v3

#1361 Change: update translations
  docs/docs/guide/commands/reset.md
  locales/README.zh-TW.md
  locales/en-US/commands.json
  locales/fr-FR/commands.json
  locales/ja/commands.json
  locales/th-TH/commands.json
  locales/zh-TW/commands.json
  locales/zh-TW/default.json
Labels: language

#1365 Update: deps
  package-lock.json
  package.json
Labels: dependencies, javascript

#1366 Update(action): bump peter-evans/create-pull-request from 4 to 5 (#1364) (cherry-picked)
  .github/workflows/minor-release.yml
  .github/workflows/patch-release.yml
Labels: dependencies, github_actions, cherry-picked

#1368 Docs: use consistent branch name in dependency badge
  README.md
Labels: documentation

#1369 Bump: package version to v4.0.0-beta.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, bump

#1371 Fix: unexpected interruption of fallbacked stream
  src/AudioSource/youtube/strategies/play-dl.ts
Labels: bug

#1372 Chore(eslint): enable `no-floating-promises`
  .eslintrc.json
  src/AudioSource/youtube/stream.ts
  src/Commands/bulkdelete.ts
  src/Commands/effect.ts
  src/Commands/import.ts
  src/Commands/invoke.ts
  src/Commands/lyrics.ts
  src/Commands/news.ts
  src/Commands/play.ts
  src/Commands/related.ts
  src/Commands/remove.ts
  src/Commands/search.ts
  src/Commands/searchqueue.ts
  src/Commands/skip.ts
  src/Component/BinaryManager.ts
  src/Component/PlayManager.ts
  src/Component/PlayManagerWithBgm.ts
  src/Component/SkipManager.ts
  src/Component/SourceCache.ts
  src/Component/backupper/mongodb.ts
  src/Component/backupper/replit.ts
  src/Component/collectors/InteractionCollector.ts
  src/Structure/GuildDataContainer.ts
  src/Structure/GuildDataContainerWithBgm.ts
  src/events/interactionCreate.ts
  src/events/messageCreate.ts
  src/events/ready.ts
  src/events/voiceChannelJoin.ts
  src/events/voiceChannelLeave.ts
  src/events/voiceChannelSwitch.ts
  src/handlers/buttonInteraction.ts
  src/index.ts
  src/logger.ts
Labels: chore

#1373 Docs: add a link to README in french
  README.md
Labels: documentation

#1376 Change: replace udp ping with ws ping
  locales/ja/commands.json
  src/Commands/ping.ts
  src/Structure/GuildDataContainer.ts
Labels: change

#1377 Docs: add french
  README.md
Labels: documentation

#1378 Fix: handle error while canceling removing last added song
  src/Component/QueueManager.ts
Labels: bug

#1379 Docs: default prefix is no longer present
  README.md
Labels: documentation

#1380 Fix: play higher quality audio
  src/AudioSource/youtube/strategies/play-dl.ts
Labels: bug

#1381 Fix: inaccurate command comparison
  src/Commands/index.ts
  src/Component/CommandManager.ts
Labels: bug

#1382 Update: deps
  package-lock.json
  package.json
Labels: dependencies, javascript

#1383 Bump: package version to v4.0.0-beta.10
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, bump

#1390 Change(i18n): sync translations from Crowdin
  docs/docs/guide/commands/play.md
  locales/README.fr-FR.md
  locales/en-US/commands.json
  locales/fr-FR/commands.json
  locales/ja/commands.json
  locales/th-TH/commands.json
  locales/zh-TW/commands.json
Labels: language

#1396 Update(docs): bump typescript from 4.9.5 to 5.0.4 in /docs (#1223, #1321, #1388) (cherry-picked)
  docs/package-lock.json
  docs/package.json
Labels: dependencies, javascript, scope:docs, cherry-picked

#1397 Update: deps
  package-lock.json
  package.json
Labels: dependencies, javascript

#1398 Fix(commands/news): button to cancel previous search
  src/Commands/news.ts
  src/Commands/search.ts
Labels: bug

#1399 Change(commands/log): make header bold
  src/Commands/log.ts
Labels: change

#1401 Fix: slice command-description in default language
  src/Commands/index.ts
Labels: bug

#1402 Feat: support miscellaneous features in play-dl environment
  src/AudioSource/youtube/index.ts
  src/AudioSource/youtube/strategies/play-dl.ts
  src/Component/PlayManager.ts
Labels: enhancement

#1404 Feat: skip syncing commands
  src/@types/node.d.ts
  src/Component/CommandManager.ts
Labels: enhancement, target:v3

#1403 Fix: skip upcoming songs
  src/Commands/skip.ts
  src/Component/PlayManager.ts
Labels: bug

#1406 Change(i18n): sync translations from Crowdin
  locales/en-US/commands.json
Labels: language

#1407 Docs: add feature showing status by nickname
  docs/docs/guide/feature/status.md
Labels: documentation

#1410 Bump: package version to v3.11.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, bump

#1412 Feat: make some commands usable when only bot in vc
  docs/docs/guide/commands/disconnect.md
  docs/docs/guide/commands/removeall.md
  locales/ja/default.json
  src/Commands/disconnect.ts
  src/Commands/index.ts
  src/Commands/removeall.ts
  src/Component/CommandManager.ts
  src/Structure/Command.ts
  src/Util/discord.ts
Labels: enhancement

#1413 Docs: add en-GB link
  README.md
Labels: documentation

#1416 Chore(crowdin.yml): change mapping of localized README files
  crowdin.yml
Labels: chore

#1417 Fix: gracefully stop streams
  src/Commands/disconnect.ts
  src/Commands/removeall.ts
  src/Commands/reset.ts
  src/Commands/rewind.ts
  src/Commands/seek.ts
  src/Commands/skip.ts
  src/Component/AudioResource.ts
  src/Component/PlayManager.ts
  src/Component/PlayManagerWithBgm.ts
  src/Component/SkipManager.ts
  src/Structure/GuildDataContainer.ts
  src/events/voiceChannelLeave.ts
Labels: bug

#1420 Feat: skip syncing commands
  src/@types/node.d.ts
  src/Component/CommandManager.ts
Labels: enhancement

#1421 Fix: not accessing db collection when db is not ready
  src/Component/backupper/mongodb.ts
Labels: bug

#1422 Bump: package version to v4.0.0-beta.12
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bump

#1424 Change: some command names
  docs/docs/guide/commands/equalplayback.md
  docs/docs/guide/commands/looponce.md
  src/Commands/equalplayback.ts
  src/Commands/looponce.ts
Labels: change

#1423 Docs: update documentation
  docs/docs/guide/feature/bulkdelete.md
  docs/docs/guide/feature/cancel.md
  docs/docs/guide/feature/language.md
  docs/docs/guide/feature/prefix.md
  docs/docs/guide/feature/search_message.md
  docs/docs/guide/feature/status.md
  docs/docs/guide/feature/super_shorten.md
  docs/docs/guide/tutorial.md
  docs/docs/setup/backup/httpbased.md
  docs/docs/setup/backup/mongo.md
  docs/docs/setup/backup/replitdb.md
  docs/docs/setup/feature/247.md
  docs/docs/setup/feature/bgm.md
  docs/docs/setup/feature/ratelimit.md
  docs/docs/setup/installation/normal.md
  docs/docs/setup/support.md
Labels: documentation

#1426 Docs(README): add link to 'supported versions' page
  README.md
Labels: documentation, target:v3

#1427 Add: new alias `equal` to `equalplayback`
  docs/docs/guide/commands/equalplayback.md
  src/Commands/equalplayback.ts
Labels: enhancement

#1430 Fix(commands/command): omit duplicated alias
  src/Commands/command.ts
Labels: bug

#1433 Chore(Docker): update base os version
  Dockerfile
Labels: chore

#1434 Fix: exceeding maximum count of autocomplete options
  src/handlers/autoCompleteInteraction.ts
Labels: bug

#1436 Change(i18n): sync translations from Crowdin
  locales/en-GB/commands.json
  locales/en-GB/default.json
  locales/en-US/commands.json
Labels: language

#1438 Update: deps
  package-lock.json
  package.json
Labels: dependencies

#1439 Fix(commands/command): autocomplete dupes
  src/Commands/command.ts
Labels: bug

#1440 Fix(commands/command): no alias
  src/Commands/command.ts
Labels: bug

#1441 Bump: package version to v4.0.0-beta.14
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bump

#1442 Fix(commands/command): unintended none label
  src/Commands/command.ts
Labels: bug

#1443 Chore(notification.js): update version
  util/notification.js
Labels: chore

#1446 Chore(config.json.sample): fix default configuration
  config.json.sample
Labels: chore

#1447 Fix: self-unsuppressing
  src/events/voiceChannelJoin.ts
Labels: bug

#1450 Bump: package version to v4.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, bump

#1456 Bump: package version to v3.11.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, bump

#1457 Chore(release-notification.yml): disable notification
  .github/workflows/release-notification.yml
Labels: chore, target:v3

#1459 Improve: make `ConfigLoader` be singleton correctly
  src/config/index.ts
Labels: Improvement

#1460 Chore(build-docker.yml): add latest tag correctly
  .github/workflows/build-docker.yml
Labels: chore, target:v3

#1451 Change(i18n): sync translations from Crowdin
  locales/fr-FR/commands.json
  locales/fr-FR/default.json
Labels: language

#1461 Chore(build-docker.yml): add latest tag correctly
  .github/workflows/build-docker.yml
Labels: chore

#1458 Bump: package version to v4.0.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, bump

#1474 Chore: add CODEOWNERS
  .github/CODEOWNERS
Labels: chore, target:v3

#1475 Fix: unable to switch vc
  package-lock.json
  src/Component/PlayManager.ts
  src/Structure/GuildDataContainer.ts
  src/events/voiceChannelSwitch.ts
Labels: bug

#1476 Fix: properties in client are not present if client is not ready
  src/index.ts
  src/server.ts
Labels: bug

#1478 Fix(normalizer): init if origin stream is present
  src/Component/streams/normalizer.ts
Labels: bug

#1479 Docs: add documentation about cache
  docs/docs/setup/feature/0-overview.md
  docs/docs/setup/feature/1-slashcommand.md
  docs/docs/setup/feature/2-ratelimit.md
  docs/docs/setup/feature/3-bgm.md
  docs/docs/setup/feature/4-247.md
  docs/docs/setup/feature/5-cache.md
  docs/versioned_docs/version-v4.0/setup/feature/cache.md
Labels: documentation

#1480 Docs: fix broken links
  docs/docs/setup/installation/configuration.md
  docs/docs/setup/installation/normal.md
Labels: documentation

#1481 Fix: reset ratelimit on reconnecting
  src/bot.ts
  src/botBase.ts
  src/events/ready.ts
Labels: bug

#1486 Fix: typo
  src/handlers/commandInteraction.ts
Labels: bug

#1487 Fix(logger): wrong tag name
  src/logger.ts
Labels: bug

#1488 Fix: errors when playing fallbacked stream
  src/AudioSource/youtube/strategies/baseYoutubeDlStrategy.ts
  src/AudioSource/youtube/stream.ts
  src/Component/AudioResource.ts
  src/Component/BinaryManager.ts
  src/Component/PlayManager.ts
  src/Util/index.ts
Labels: bug

#1490 Docs: fix incosistent words
  docs/docs/setup/feature/5-cache.md
Labels: documentation

#1498 Chore(eslint): configure `no-unused-imports`
  .eslintrc.json
  package-lock.json
  package.json
  src/Commands/index.ts
  src/Commands/search.ts
Labels: chore

#1491 Bump: package version to v4.0.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, bump

#1500 Fix: instantly force-stop on failed to play streams
  src/Component/PlayManager.ts
  src/Component/streams/normalizer.ts
Labels: bug

#1502 Chore(dependabot.yml): add v3 label to PRs being based on v3
  .github/dependabot.yml
Labels: chore

#1509 Docs: add support for Node.js v20
  docs/docs/setup/installation/normal.md
  docs/versioned_docs/version-v4.0/setup/installation/normal.md
Labels: documentation

#1530 Docs: installation ways order
  docs/docs/setup/installation/docker-compose.md
  docs/docs/setup/installation/normal.md
  docs/versioned_docs/version-v4.0/setup/installation/docker-compose.md
  docs/versioned_docs/version-v4.0/setup/installation/normal.md
Labels: documentation

#1532 Chore: workflow for lts
  .github/dependabot.yml
Labels: chore

#1533 Chore(lts): removed "test"&"dependa" and update test-wf
  .github/dependabot.yml
  .github/workflows/test.yml
  .github/workflows/testing.yml
Labels: target:v1

#1543 Chore(test.yml): fix invalid workflow
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: chore, target:v1

#1544 Revert: "Update(docs): Bump prism-react-renderer from 1.3.5 to 2.0.3 in /docs"
  docs/package-lock.json
  docs/package.json
Labels: documentation, chore, target:v3
